const actionTypes = {
    ADD_MOVIE: "ADD_MOVIE",
    DELETE_MOVIE:"DELETE_MOVIE",
    UPDATE_MOVIE:"UPDATE_MOVIE",
    SEARCH_KEYWORD:"SEARCH_KEYWORD",
    MIN_RATING:"MIN_RATING"
}
export default actionTypes